# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/welcome.ipynb
"""

pip install streamlit

!pip install streamlit
import streamlit as st

import requests
from bs4 import BeautifulSoup
import subprocess
subprocess.run(["pip", "install", "streamlit"])


st.title("🌐 Simple Web Scraper")

# Input box for user to enter URL
url = st.text_input("https://sellercentral.amazon.in/")

if url:
    try:
        # Fetch the page
        response = requests.get(url)
        response.raise_for_status()  # check for errors

        # Parse with BeautifulSoup
        soup = BeautifulSoup(response.text, "html.parser")

        # Extract title
        title = soup.title.string if soup.title else "No title found"

        st.success(f"✅ Title of the page: {title}")

    except Exception as e:
        st.error(f"❌ Error: {e}")