# -*- coding: utf-8 -*-
"""Untitled31.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W1hZYu_H40_LtKEUBPgOSbhpJXNnUPxo
"""

import streamlit as st
import requests
from bs4 import BeautifulSoup

st.title("🌐 Simple Web Scraper")

# Input box for URL
url = st.text_input("Enter website URL:", "https://sellercentral.amazon.in/")

if url:
    try:
        # Send HTTP request
        response = requests.get(url, timeout=5)
        response.raise_for_status()

        # Parse with BeautifulSoup
        soup = BeautifulSoup(response.text, "html.parser")

        # Get website title
        title = soup.title.string if soup.title else "No title found"

        st.success(f"Website Title: {title}")

    except Exception as e:
        st.error(f"Error: {e}")

else:
    st.info("https://sellercentral.amazon.in/")

# Commented out IPython magic to ensure Python compatibility.
# %pip install streamlit